Repository ayrna/dlordinal, pull requests merged in 2024-07, with the labels that each got.

#75 [ENH] Added to array and probas to preds castings in metrics
  dlordinal/metrics/metrics.py
Labels: enhancement

#76 [DOC] Completed code examples in metrics doc
  dlordinal/metrics/metrics.py
Labels: documentation

#77 [DOC] Adding references to metrics doc
  dlordinal/metrics/metrics.py
  docs/references.bib
Labels: documentation

#79 [API] `Adience` class interface changes to match `VisionDataset`
  build_tools/run_tutorials.sh
  dlordinal/datasets/adience.py
  dlordinal/datasets/tests/test_adience.py
  tutorials/adience_tutorial.ipynb
  tutorials/datasets_tutorial.ipynb
Labels: API design

#78 [API] `FGNet` interface changes to match `VisionDataset`
  dlordinal/datasets/fgnet.py
  dlordinal/datasets/tests/test_fgnet.py
  tutorials/dlordinal_with_skorch_tutorial.ipynb
  tutorials/ecoc_tutorial.ipynb
  tutorials/fgnet_tutorial.ipynb
  tutorials/hybrid_dropout_tutorial.ipynb
  tutorials/losses_tutorial.ipynb
  tutorials/stick_breaking_tutorial.ipynb
Labels: API design

#81 [DOC] Readme update
  README.md
Labels: documentation

#82 [MNT] Updated github actions workflows
  .github/workflows/run_tests.yml
  .github/workflows/tutorials.yml
  README.md
Labels: maintenance
