Repository ayrna/dlordinal, pull requests merged in 2025-01, with the labels that each got.

#89 [MNT] Update pre-commit configuration
  .pre-commit-config.yaml
  dlordinal/datasets/__init__.py
  dlordinal/dropout/tests/__init__.py
  dlordinal/metrics/__init__.py
  dlordinal/metrics/tests/test_metrics.py
  dlordinal/wrappers/obd_ecoc.py
  tutorials/adience_tutorial.ipynb
  tutorials/dlordinal_with_skorch_tutorial.ipynb
  tutorials/ecoc_tutorial.ipynb
  tutorials/fgnet_tutorial.ipynb
  tutorials/hybrid_dropout_tutorial.ipynb
  tutorials/losses_tutorial.ipynb
  tutorials/stick_breaking_tutorial.ipynb
Labels: maintenance

#91 [MNT] pre-commit workflow
  .github/workflows/pr_precommit.yml
Labels: maintenance

#92 [MNT] Release v2.3.0
  .github/workflows/fast_release.yml
  .github/workflows/release.yml
  .github/workflows/run_tests.yml
  README.md
  build_tools/run_skorch_tutorials.sh
  dlordinal/__init__.py
  dlordinal/datasets/adience.py
  docs/conf.py
  pyproject.toml
Labels: maintenance, release

#93 [BUG] Added support for any number of classes in `get_binomial_soft_labels()`
  dlordinal/soft_labelling/binomial_distribution.py
  dlordinal/soft_labelling/tests/test_binomial_distribution.py
Labels: bug

#96 Release v2.3.2
  CHANGELOG.md
  README.md
  changelog_versions/version_2-3-0.md
  changelog_versions/version_2-3-2.md
  dlordinal/__init__.py
  docs/conf.py
  pyproject.toml
Labels: release
